import type { Metadata } from "next";
import "./globals.css";
import { root } from "melony";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return root({
    children: [children],
    shouldRenderHtml: true,
    // className: geistSans.className + " " + geistMono.className,
    navigate: async (path) => {
      "use server";
      redirect(path);
    },
  });
}
